name: Tests

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: bash
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup score-compose
      uses: ./
      with:
        file: score-compose
        version: ${{ matrix.version }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup score-k8s
      uses: ./
      with:
        file: score-k8s
        version: ${{ matrix.version }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify installation
      run: |
        export SCORE_CS_VERSION=$( score-compose --version )
        export SCORE_KS_VERSION=$( score-k8s --version )
