name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [0.6.0, latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup score-compose
      uses: ./
      with:
        file: score-compose
        version: ${{ matrix.version }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup score-humanitec
      uses: ./
      with:
        file: score-humanitec
        version: ${{ matrix.version }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup score-helm
      uses: ./
      with:
        file: score-helm
        version: ${{ matrix.version }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify installation
      run: |
        export SCORE_CS_VERSION=$( score-compose --version )
        export SCORE_HT_VERSION=$( score-humanitec --version )
        export SCORE_HM_VERSION=$( score-helm --version )
